version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGODB_URL: "mongodb+srv://MoZaki:thisIsASecret@organizationmanager.m1dpzkn.mongodb.net/?retryWrites=true&w=majority"
      SECRET_KEY: "thisIsASecret"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
